### ISSUE TITLE
Test 10

### ISSUE THREAD

**Issue by gregoirebois** [gregoirebois/console.unito.io-test#4]
Test pour labels et milestones

**Comment by gregoirebois** [comment]
ca fonctionne bien!

[--- Linked with ASANA.com using Unito.io
#commenter Gregoire Bois
---[aa]

**Comment by gregoirebois** [comment]
Je trouve aussi !

[--- Linked with ASANA.com using Unito.io
#commenter John
---[aa]

**Comment by gregoirebois** [comment]
Je ne sais pas qui a fait ça, mais c'est du solide!

**Comment by jaecSolutions** [comment]
Hahaha! Great ! Sell it now!

**Comment by gregoirebois** [comment]
Amazing tool!

[--- Linked with ASANA.com using Unito.io
#commenter John
---[aa]
